// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as SqliteTypes } from '@prisma/orm-sqlite/adapter/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-sqlite/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-sqlite/contract/types';

export type StorageHash =
  StorageHashBase<'9ca036b9802306b4ccb9bcfca926854d0c106140b5e51b954cd79198b74b6157'>;
export type ExecutionHash =
  ExecutionHashBase<'7aec38981bbbc3bed9016a5d0640b6933388538d1060b5f4a43ab1f06b333b33'>;
export type ProfileHash =
  ProfileHashBase<'260b8608d1aacaf1f690779a6cff39a12947c599597c5ba464ca75b9e775df53'>;

export type CodecTypes = SqliteTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = Record<string, never>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/real@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'sqlite/bigintnumber@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'sqlite/bigintnumber@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'sqlite/bigint@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'sqlite/bigint@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/blob@1': { readonly output: 'sqlite/blob@1'; readonly nullable: true };
      readonly 'sqlite/datetime@1': {
        readonly output: 'sqlite/datetime@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/integer@1'; readonly nullable: true };
      readonly 'sqlite/json@1': { readonly output: 'sqlite/json@1'; readonly nullable: true };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/text@1': { readonly output: 'sqlite/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/blob@1': { readonly output: 'sqlite/blob@1'; readonly nullable: true };
      readonly 'sqlite/datetime@1': {
        readonly output: 'sqlite/datetime@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/integer@1'; readonly nullable: true };
      readonly 'sqlite/json@1': { readonly output: 'sqlite/json@1'; readonly nullable: true };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/text@1': { readonly output: 'sqlite/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sqlite/bigintnumber@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'sql/int@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigint@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly AppSetting: {
      readonly key: CodecTypes['sqlite/text@1']['output'];
      readonly value: CodecTypes['sqlite/text@1']['output'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['output'];
    };
    readonly BetSlip: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly userId: CodecTypes['sqlite/text@1']['output'];
      readonly tipId: CodecTypes['sqlite/text@1']['output'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
    };
    readonly Bookmark: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly userId: CodecTypes['sqlite/text@1']['output'];
      readonly tipId: CodecTypes['sqlite/text@1']['output'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
    };
    readonly Newsletter: {
      readonly id: CodecTypes['sqlite/integer@1']['output'];
      readonly email: CodecTypes['sqlite/text@1']['output'];
      readonly subscribedAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly active: CodecTypes['sqlite/integer@1']['output'];
    };
    readonly Payment: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly userId: CodecTypes['sqlite/text@1']['output'] | null;
      readonly email: CodecTypes['sqlite/text@1']['output'];
      readonly amount: CodecTypes['sqlite/integer@1']['output'];
      readonly plan: CodecTypes['sqlite/text@1']['output'];
      readonly reference: CodecTypes['sqlite/text@1']['output'];
      readonly accessCode: CodecTypes['sqlite/text@1']['output'] | null;
      readonly status: CodecTypes['sqlite/text@1']['output'];
      readonly channel: CodecTypes['sqlite/text@1']['output'] | null;
      readonly paidAt: CodecTypes['sqlite/datetime@1']['output'] | null;
      readonly expiresAt: CodecTypes['sqlite/datetime@1']['output'] | null;
      readonly metadata: CodecTypes['sqlite/text@1']['output'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['output'];
    };
    readonly PlacedBet: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly userId: CodecTypes['sqlite/text@1']['output'] | null;
      readonly email: CodecTypes['sqlite/text@1']['output'];
      readonly betType: CodecTypes['sqlite/text@1']['output'];
      readonly legs: CodecTypes['sqlite/text@1']['output'];
      readonly stake: CodecTypes['sqlite/integer@1']['output'];
      readonly totalOdds: CodecTypes['sqlite/real@1']['output'];
      readonly potentialReturn: CodecTypes['sqlite/integer@1']['output'];
      readonly status: CodecTypes['sqlite/text@1']['output'];
      readonly result: CodecTypes['sqlite/text@1']['output'] | null;
      readonly settledAt: CodecTypes['sqlite/datetime@1']['output'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['output'];
    };
    readonly Referral: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly code: CodecTypes['sqlite/text@1']['output'];
      readonly referrerId: CodecTypes['sqlite/text@1']['output'];
      readonly referredId: CodecTypes['sqlite/text@1']['output'];
      readonly status: CodecTypes['sqlite/text@1']['output'];
      readonly rewardDays: CodecTypes['sqlite/integer@1']['output'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly qualifiedAt: CodecTypes['sqlite/datetime@1']['output'] | null;
      readonly rewardedAt: CodecTypes['sqlite/datetime@1']['output'] | null;
    };
    readonly SharedSlip: {
      readonly slug: CodecTypes['sqlite/text@1']['output'];
      readonly email: CodecTypes['sqlite/text@1']['output'] | null;
      readonly legs: CodecTypes['sqlite/text@1']['output'];
      readonly stake: CodecTypes['sqlite/integer@1']['output'] | null;
      readonly totalOdds: CodecTypes['sqlite/real@1']['output'] | null;
      readonly potentialReturn: CodecTypes['sqlite/integer@1']['output'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
    };
    readonly Tip: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly league: CodecTypes['sqlite/text@1']['output'];
      readonly country: CodecTypes['sqlite/text@1']['output'];
      readonly flag: CodecTypes['sqlite/text@1']['output'];
      readonly homeTeam: CodecTypes['sqlite/text@1']['output'];
      readonly awayTeam: CodecTypes['sqlite/text@1']['output'];
      readonly matchTime: CodecTypes['sqlite/text@1']['output'];
      readonly predictionType: CodecTypes['sqlite/text@1']['output'];
      readonly prediction: CodecTypes['sqlite/text@1']['output'];
      readonly odds: CodecTypes['sqlite/text@1']['output'];
      readonly confidence: CodecTypes['sqlite/integer@1']['output'];
      readonly confidenceLabel: CodecTypes['sqlite/text@1']['output'];
      readonly status: CodecTypes['sqlite/text@1']['output'];
      readonly tipster: CodecTypes['sqlite/text@1']['output'];
      readonly isPremium: CodecTypes['sqlite/integer@1']['output'];
      readonly analysis: CodecTypes['sqlite/text@1']['output'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['output'];
    };
    readonly User: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly email: CodecTypes['sqlite/text@1']['output'];
      readonly name: CodecTypes['sqlite/text@1']['output'] | null;
      readonly password: CodecTypes['sqlite/text@1']['output'] | null;
      readonly image: CodecTypes['sqlite/text@1']['output'] | null;
      readonly plan: CodecTypes['sqlite/text@1']['output'];
      readonly referralCode: CodecTypes['sqlite/text@1']['output'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly AppSetting: {
      readonly key: CodecTypes['sqlite/text@1']['input'];
      readonly value: CodecTypes['sqlite/text@1']['input'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['input'];
    };
    readonly BetSlip: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly userId: CodecTypes['sqlite/text@1']['input'];
      readonly tipId: CodecTypes['sqlite/text@1']['input'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
    };
    readonly Bookmark: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly userId: CodecTypes['sqlite/text@1']['input'];
      readonly tipId: CodecTypes['sqlite/text@1']['input'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
    };
    readonly Newsletter: {
      readonly id: CodecTypes['sqlite/integer@1']['input'];
      readonly email: CodecTypes['sqlite/text@1']['input'];
      readonly subscribedAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly active: CodecTypes['sqlite/integer@1']['input'];
    };
    readonly Payment: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly userId: CodecTypes['sqlite/text@1']['input'] | null;
      readonly email: CodecTypes['sqlite/text@1']['input'];
      readonly amount: CodecTypes['sqlite/integer@1']['input'];
      readonly plan: CodecTypes['sqlite/text@1']['input'];
      readonly reference: CodecTypes['sqlite/text@1']['input'];
      readonly accessCode: CodecTypes['sqlite/text@1']['input'] | null;
      readonly status: CodecTypes['sqlite/text@1']['input'];
      readonly channel: CodecTypes['sqlite/text@1']['input'] | null;
      readonly paidAt: CodecTypes['sqlite/datetime@1']['input'] | null;
      readonly expiresAt: CodecTypes['sqlite/datetime@1']['input'] | null;
      readonly metadata: CodecTypes['sqlite/text@1']['input'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['input'];
    };
    readonly PlacedBet: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly userId: CodecTypes['sqlite/text@1']['input'] | null;
      readonly email: CodecTypes['sqlite/text@1']['input'];
      readonly betType: CodecTypes['sqlite/text@1']['input'];
      readonly legs: CodecTypes['sqlite/text@1']['input'];
      readonly stake: CodecTypes['sqlite/integer@1']['input'];
      readonly totalOdds: CodecTypes['sqlite/real@1']['input'];
      readonly potentialReturn: CodecTypes['sqlite/integer@1']['input'];
      readonly status: CodecTypes['sqlite/text@1']['input'];
      readonly result: CodecTypes['sqlite/text@1']['input'] | null;
      readonly settledAt: CodecTypes['sqlite/datetime@1']['input'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['input'];
    };
    readonly Referral: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly code: CodecTypes['sqlite/text@1']['input'];
      readonly referrerId: CodecTypes['sqlite/text@1']['input'];
      readonly referredId: CodecTypes['sqlite/text@1']['input'];
      readonly status: CodecTypes['sqlite/text@1']['input'];
      readonly rewardDays: CodecTypes['sqlite/integer@1']['input'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly qualifiedAt: CodecTypes['sqlite/datetime@1']['input'] | null;
      readonly rewardedAt: CodecTypes['sqlite/datetime@1']['input'] | null;
    };
    readonly SharedSlip: {
      readonly slug: CodecTypes['sqlite/text@1']['input'];
      readonly email: CodecTypes['sqlite/text@1']['input'] | null;
      readonly legs: CodecTypes['sqlite/text@1']['input'];
      readonly stake: CodecTypes['sqlite/integer@1']['input'] | null;
      readonly totalOdds: CodecTypes['sqlite/real@1']['input'] | null;
      readonly potentialReturn: CodecTypes['sqlite/integer@1']['input'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
    };
    readonly Tip: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly league: CodecTypes['sqlite/text@1']['input'];
      readonly country: CodecTypes['sqlite/text@1']['input'];
      readonly flag: CodecTypes['sqlite/text@1']['input'];
      readonly homeTeam: CodecTypes['sqlite/text@1']['input'];
      readonly awayTeam: CodecTypes['sqlite/text@1']['input'];
      readonly matchTime: CodecTypes['sqlite/text@1']['input'];
      readonly predictionType: CodecTypes['sqlite/text@1']['input'];
      readonly prediction: CodecTypes['sqlite/text@1']['input'];
      readonly odds: CodecTypes['sqlite/text@1']['input'];
      readonly confidence: CodecTypes['sqlite/integer@1']['input'];
      readonly confidenceLabel: CodecTypes['sqlite/text@1']['input'];
      readonly status: CodecTypes['sqlite/text@1']['input'];
      readonly tipster: CodecTypes['sqlite/text@1']['input'];
      readonly isPremium: CodecTypes['sqlite/integer@1']['input'];
      readonly analysis: CodecTypes['sqlite/text@1']['input'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['input'];
    };
    readonly User: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly email: CodecTypes['sqlite/text@1']['input'];
      readonly name: CodecTypes['sqlite/text@1']['input'] | null;
      readonly password: CodecTypes['sqlite/text@1']['input'] | null;
      readonly image: CodecTypes['sqlite/text@1']['input'] | null;
      readonly plan: CodecTypes['sqlite/text@1']['input'];
      readonly referralCode: CodecTypes['sqlite/text@1']['input'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly __unbound__: {
    readonly AppSetting: {
      readonly key: CodecTypes['sqlite/text@1']['output'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly value: CodecTypes['sqlite/text@1']['output'];
    };
    readonly BetSlip: {
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly tipId: CodecTypes['sqlite/text@1']['output'];
      readonly userId: CodecTypes['sqlite/text@1']['output'];
    };
    readonly Bookmark: {
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly tipId: CodecTypes['sqlite/text@1']['output'];
      readonly userId: CodecTypes['sqlite/text@1']['output'];
    };
    readonly Newsletter: {
      readonly active: CodecTypes['sqlite/integer@1']['output'];
      readonly email: CodecTypes['sqlite/text@1']['output'];
      readonly id: CodecTypes['sqlite/integer@1']['output'];
      readonly subscribedAt: CodecTypes['sqlite/datetime@1']['output'];
    };
    readonly Payment: {
      readonly accessCode: CodecTypes['sqlite/text@1']['output'] | null;
      readonly amount: CodecTypes['sqlite/integer@1']['output'];
      readonly channel: CodecTypes['sqlite/text@1']['output'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly email: CodecTypes['sqlite/text@1']['output'];
      readonly expiresAt: CodecTypes['sqlite/datetime@1']['output'] | null;
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly metadata: CodecTypes['sqlite/text@1']['output'] | null;
      readonly paidAt: CodecTypes['sqlite/datetime@1']['output'] | null;
      readonly plan: CodecTypes['sqlite/text@1']['output'];
      readonly reference: CodecTypes['sqlite/text@1']['output'];
      readonly status: CodecTypes['sqlite/text@1']['output'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly userId: CodecTypes['sqlite/text@1']['output'] | null;
    };
    readonly PlacedBet: {
      readonly betType: CodecTypes['sqlite/text@1']['output'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly email: CodecTypes['sqlite/text@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly legs: CodecTypes['sqlite/text@1']['output'];
      readonly potentialReturn: CodecTypes['sqlite/integer@1']['output'];
      readonly result: CodecTypes['sqlite/text@1']['output'] | null;
      readonly settledAt: CodecTypes['sqlite/datetime@1']['output'] | null;
      readonly stake: CodecTypes['sqlite/integer@1']['output'];
      readonly status: CodecTypes['sqlite/text@1']['output'];
      readonly totalOdds: CodecTypes['sqlite/real@1']['output'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly userId: CodecTypes['sqlite/text@1']['output'] | null;
    };
    readonly Referral: {
      readonly code: CodecTypes['sqlite/text@1']['output'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly qualifiedAt: CodecTypes['sqlite/datetime@1']['output'] | null;
      readonly referredId: CodecTypes['sqlite/text@1']['output'];
      readonly referrerId: CodecTypes['sqlite/text@1']['output'];
      readonly rewardDays: CodecTypes['sqlite/integer@1']['output'];
      readonly rewardedAt: CodecTypes['sqlite/datetime@1']['output'] | null;
      readonly status: CodecTypes['sqlite/text@1']['output'];
    };
    readonly SharedSlip: {
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly email: CodecTypes['sqlite/text@1']['output'] | null;
      readonly legs: CodecTypes['sqlite/text@1']['output'];
      readonly potentialReturn: CodecTypes['sqlite/integer@1']['output'] | null;
      readonly slug: CodecTypes['sqlite/text@1']['output'];
      readonly stake: CodecTypes['sqlite/integer@1']['output'] | null;
      readonly totalOdds: CodecTypes['sqlite/real@1']['output'] | null;
    };
    readonly Tip: {
      readonly analysis: CodecTypes['sqlite/text@1']['output'] | null;
      readonly awayTeam: CodecTypes['sqlite/text@1']['output'];
      readonly confidence: CodecTypes['sqlite/integer@1']['output'];
      readonly confidenceLabel: CodecTypes['sqlite/text@1']['output'];
      readonly country: CodecTypes['sqlite/text@1']['output'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly flag: CodecTypes['sqlite/text@1']['output'];
      readonly homeTeam: CodecTypes['sqlite/text@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly isPremium: CodecTypes['sqlite/integer@1']['output'];
      readonly league: CodecTypes['sqlite/text@1']['output'];
      readonly matchTime: CodecTypes['sqlite/text@1']['output'];
      readonly odds: CodecTypes['sqlite/text@1']['output'];
      readonly prediction: CodecTypes['sqlite/text@1']['output'];
      readonly predictionType: CodecTypes['sqlite/text@1']['output'];
      readonly status: CodecTypes['sqlite/text@1']['output'];
      readonly tipster: CodecTypes['sqlite/text@1']['output'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['output'];
    };
    readonly User: {
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly email: CodecTypes['sqlite/text@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly image: CodecTypes['sqlite/text@1']['output'] | null;
      readonly name: CodecTypes['sqlite/text@1']['output'] | null;
      readonly password: CodecTypes['sqlite/text@1']['output'] | null;
      readonly plan: CodecTypes['sqlite/text@1']['output'];
      readonly referralCode: CodecTypes['sqlite/text@1']['output'] | null;
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly __unbound__: {
    readonly AppSetting: {
      readonly key: CodecTypes['sqlite/text@1']['input'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly value: CodecTypes['sqlite/text@1']['input'];
    };
    readonly BetSlip: {
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly tipId: CodecTypes['sqlite/text@1']['input'];
      readonly userId: CodecTypes['sqlite/text@1']['input'];
    };
    readonly Bookmark: {
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly tipId: CodecTypes['sqlite/text@1']['input'];
      readonly userId: CodecTypes['sqlite/text@1']['input'];
    };
    readonly Newsletter: {
      readonly active: CodecTypes['sqlite/integer@1']['input'];
      readonly email: CodecTypes['sqlite/text@1']['input'];
      readonly id: CodecTypes['sqlite/integer@1']['input'];
      readonly subscribedAt: CodecTypes['sqlite/datetime@1']['input'];
    };
    readonly Payment: {
      readonly accessCode: CodecTypes['sqlite/text@1']['input'] | null;
      readonly amount: CodecTypes['sqlite/integer@1']['input'];
      readonly channel: CodecTypes['sqlite/text@1']['input'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly email: CodecTypes['sqlite/text@1']['input'];
      readonly expiresAt: CodecTypes['sqlite/datetime@1']['input'] | null;
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly metadata: CodecTypes['sqlite/text@1']['input'] | null;
      readonly paidAt: CodecTypes['sqlite/datetime@1']['input'] | null;
      readonly plan: CodecTypes['sqlite/text@1']['input'];
      readonly reference: CodecTypes['sqlite/text@1']['input'];
      readonly status: CodecTypes['sqlite/text@1']['input'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly userId: CodecTypes['sqlite/text@1']['input'] | null;
    };
    readonly PlacedBet: {
      readonly betType: CodecTypes['sqlite/text@1']['input'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly email: CodecTypes['sqlite/text@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly legs: CodecTypes['sqlite/text@1']['input'];
      readonly potentialReturn: CodecTypes['sqlite/integer@1']['input'];
      readonly result: CodecTypes['sqlite/text@1']['input'] | null;
      readonly settledAt: CodecTypes['sqlite/datetime@1']['input'] | null;
      readonly stake: CodecTypes['sqlite/integer@1']['input'];
      readonly status: CodecTypes['sqlite/text@1']['input'];
      readonly totalOdds: CodecTypes['sqlite/real@1']['input'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly userId: CodecTypes['sqlite/text@1']['input'] | null;
    };
    readonly Referral: {
      readonly code: CodecTypes['sqlite/text@1']['input'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly qualifiedAt: CodecTypes['sqlite/datetime@1']['input'] | null;
      readonly referredId: CodecTypes['sqlite/text@1']['input'];
      readonly referrerId: CodecTypes['sqlite/text@1']['input'];
      readonly rewardDays: CodecTypes['sqlite/integer@1']['input'];
      readonly rewardedAt: CodecTypes['sqlite/datetime@1']['input'] | null;
      readonly status: CodecTypes['sqlite/text@1']['input'];
    };
    readonly SharedSlip: {
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly email: CodecTypes['sqlite/text@1']['input'] | null;
      readonly legs: CodecTypes['sqlite/text@1']['input'];
      readonly potentialReturn: CodecTypes['sqlite/integer@1']['input'] | null;
      readonly slug: CodecTypes['sqlite/text@1']['input'];
      readonly stake: CodecTypes['sqlite/integer@1']['input'] | null;
      readonly totalOdds: CodecTypes['sqlite/real@1']['input'] | null;
    };
    readonly Tip: {
      readonly analysis: CodecTypes['sqlite/text@1']['input'] | null;
      readonly awayTeam: CodecTypes['sqlite/text@1']['input'];
      readonly confidence: CodecTypes['sqlite/integer@1']['input'];
      readonly confidenceLabel: CodecTypes['sqlite/text@1']['input'];
      readonly country: CodecTypes['sqlite/text@1']['input'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly flag: CodecTypes['sqlite/text@1']['input'];
      readonly homeTeam: CodecTypes['sqlite/text@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly isPremium: CodecTypes['sqlite/integer@1']['input'];
      readonly league: CodecTypes['sqlite/text@1']['input'];
      readonly matchTime: CodecTypes['sqlite/text@1']['input'];
      readonly odds: CodecTypes['sqlite/text@1']['input'];
      readonly prediction: CodecTypes['sqlite/text@1']['input'];
      readonly predictionType: CodecTypes['sqlite/text@1']['input'];
      readonly status: CodecTypes['sqlite/text@1']['input'];
      readonly tipster: CodecTypes['sqlite/text@1']['input'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['input'];
    };
    readonly User: {
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly email: CodecTypes['sqlite/text@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly image: CodecTypes['sqlite/text@1']['input'] | null;
      readonly name: CodecTypes['sqlite/text@1']['input'] | null;
      readonly password: CodecTypes['sqlite/text@1']['input'] | null;
      readonly plan: CodecTypes['sqlite/text@1']['input'];
      readonly referralCode: CodecTypes['sqlite/text@1']['input'] | null;
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'sqlite-namespace';
        readonly entries: {
          readonly table: {
            readonly AppSetting: {
              columns: {
                readonly key: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly value: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly updatedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['key'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly BetSlip: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly tipId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'BetSlip_userId_idx_a489d58a';
                  readonly prefix: 'BetSlip_userId_idx';
                  readonly columns: readonly ['userId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'BetSlip_tipId_idx_17f3bc97';
                  readonly prefix: 'BetSlip_tipId_idx';
                  readonly columns: readonly ['tipId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'BetSlip';
                    readonly columns: readonly ['userId'];
                  };
                  readonly target: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'User';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'BetSlip';
                    readonly columns: readonly ['tipId'];
                  };
                  readonly target: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'Tip';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly Bookmark: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly tipId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['userId', 'tipId'] }];
              indexes: readonly [
                {
                  readonly name: 'Bookmark_userId_idx_a489d58a';
                  readonly prefix: 'Bookmark_userId_idx';
                  readonly columns: readonly ['userId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'Bookmark_tipId_idx_17f3bc97';
                  readonly prefix: 'Bookmark_tipId_idx';
                  readonly columns: readonly ['tipId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'Bookmark';
                    readonly columns: readonly ['userId'];
                  };
                  readonly target: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'User';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'Bookmark';
                    readonly columns: readonly ['tipId'];
                  };
                  readonly target: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'Tip';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly Newsletter: {
              columns: {
                readonly id: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly subscribedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly active: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/integer@1', 1>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly Payment: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly amount: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                };
                readonly plan: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly reference: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly accessCode: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/text@1', 'pending'>;
                  };
                };
                readonly channel: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly paidAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: true;
                };
                readonly expiresAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: true;
                };
                readonly metadata: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['reference'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly PlacedBet: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly betType: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly legs: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly stake: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                };
                readonly totalOdds: {
                  readonly nativeType: 'real';
                  readonly codecId: 'sqlite/real@1';
                  readonly nullable: false;
                };
                readonly potentialReturn: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/text@1', 'pending'>;
                  };
                };
                readonly result: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly settledAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly Referral: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly code: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly referrerId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly referredId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/text@1', 'pending'>;
                  };
                };
                readonly rewardDays: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/integer@1', 7>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly qualifiedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: true;
                };
                readonly rewardedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['referredId'] }];
              indexes: readonly [
                {
                  readonly name: 'Referral_referrerId_idx_cac6d89f';
                  readonly prefix: 'Referral_referrerId_idx';
                  readonly columns: readonly ['referrerId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'Referral';
                    readonly columns: readonly ['referrerId'];
                  };
                  readonly target: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'User';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'Referral';
                    readonly columns: readonly ['referredId'];
                  };
                  readonly target: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'User';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly SharedSlip: {
              columns: {
                readonly slug: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly legs: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly stake: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: true;
                };
                readonly totalOdds: {
                  readonly nativeType: 'real';
                  readonly codecId: 'sqlite/real@1';
                  readonly nullable: true;
                };
                readonly potentialReturn: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['slug'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'SharedSlip_email_idx_46df9cad';
                  readonly prefix: 'SharedSlip_email_idx';
                  readonly columns: readonly ['email'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly Tip: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly league: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly country: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly flag: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/text@1', '⚽'>;
                  };
                };
                readonly homeTeam: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly awayTeam: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly matchTime: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly predictionType: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly prediction: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly odds: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly confidence: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                };
                readonly confidenceLabel: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/text@1', 'upcoming'>;
                  };
                };
                readonly tipster: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly isPremium: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/integer@1', 0>;
                  };
                };
                readonly analysis: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly User: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly password: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly image: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly plan: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/text@1', 'free'>;
                  };
                };
                readonly referralCode: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['email'] },
                { readonly columns: readonly ['referralCode'] },
              ];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'sqlite';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly User: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'User' };
    readonly Referral: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Referral';
    };
    readonly Bookmark: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Bookmark';
    };
    readonly Tip: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Tip' };
    readonly BetSlip: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'BetSlip';
    };
    readonly Newsletter: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Newsletter';
    };
    readonly Payment: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Payment';
    };
    readonly PlacedBet: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'PlacedBet';
    };
    readonly AppSetting: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'AppSetting';
    };
    readonly SharedSlip: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'SharedSlip';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly AppSetting: {
            readonly fields: {
              readonly key: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly value: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'AppSetting';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly key: { readonly column: 'key' };
                readonly value: { readonly column: 'value' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly BetSlip: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly tipId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: {
              readonly tip: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Tip';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['tipId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly user: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'BetSlip';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly userId: { readonly column: 'userId' };
                readonly tipId: { readonly column: 'tipId' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly Bookmark: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly tipId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: {
              readonly tip: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Tip';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['tipId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly user: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Bookmark';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly userId: { readonly column: 'userId' };
                readonly tipId: { readonly column: 'tipId' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly Newsletter: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly subscribedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
              readonly active: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'Newsletter';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly email: { readonly column: 'email' };
                readonly subscribedAt: { readonly column: 'subscribedAt' };
                readonly active: { readonly column: 'active' };
              };
            };
          };
          readonly Payment: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly userId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly amount: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
              readonly plan: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly reference: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly accessCode: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly channel: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly paidAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
              readonly expiresAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
              readonly metadata: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'Payment';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly userId: { readonly column: 'userId' };
                readonly email: { readonly column: 'email' };
                readonly amount: { readonly column: 'amount' };
                readonly plan: { readonly column: 'plan' };
                readonly reference: { readonly column: 'reference' };
                readonly accessCode: { readonly column: 'accessCode' };
                readonly status: { readonly column: 'status' };
                readonly channel: { readonly column: 'channel' };
                readonly paidAt: { readonly column: 'paidAt' };
                readonly expiresAt: { readonly column: 'expiresAt' };
                readonly metadata: { readonly column: 'metadata' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly PlacedBet: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly userId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly betType: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly legs: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly stake: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
              readonly totalOdds: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/real@1' };
              };
              readonly potentialReturn: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly result: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly settledAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'PlacedBet';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly userId: { readonly column: 'userId' };
                readonly email: { readonly column: 'email' };
                readonly betType: { readonly column: 'betType' };
                readonly legs: { readonly column: 'legs' };
                readonly stake: { readonly column: 'stake' };
                readonly totalOdds: { readonly column: 'totalOdds' };
                readonly potentialReturn: { readonly column: 'potentialReturn' };
                readonly status: { readonly column: 'status' };
                readonly result: { readonly column: 'result' };
                readonly settledAt: { readonly column: 'settledAt' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Referral: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly code: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly referrerId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly referredId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly rewardDays: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
              readonly qualifiedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
              readonly rewardedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: {
              readonly referred: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['referredId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly referrer: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['referrerId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Referral';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly code: { readonly column: 'code' };
                readonly referrerId: { readonly column: 'referrerId' };
                readonly referredId: { readonly column: 'referredId' };
                readonly status: { readonly column: 'status' };
                readonly rewardDays: { readonly column: 'rewardDays' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly qualifiedAt: { readonly column: 'qualifiedAt' };
                readonly rewardedAt: { readonly column: 'rewardedAt' };
              };
            };
          };
          readonly SharedSlip: {
            readonly fields: {
              readonly slug: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly email: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly legs: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly stake: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
              readonly totalOdds: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/real@1' };
              };
              readonly potentialReturn: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'SharedSlip';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly slug: { readonly column: 'slug' };
                readonly email: { readonly column: 'email' };
                readonly legs: { readonly column: 'legs' };
                readonly stake: { readonly column: 'stake' };
                readonly totalOdds: { readonly column: 'totalOdds' };
                readonly potentialReturn: { readonly column: 'potentialReturn' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly Tip: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly league: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly country: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly flag: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly homeTeam: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly awayTeam: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly matchTime: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly predictionType: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly prediction: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly odds: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly confidence: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
              readonly confidenceLabel: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly tipster: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly isPremium: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
              readonly analysis: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'Tip';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly league: { readonly column: 'league' };
                readonly country: { readonly column: 'country' };
                readonly flag: { readonly column: 'flag' };
                readonly homeTeam: { readonly column: 'homeTeam' };
                readonly awayTeam: { readonly column: 'awayTeam' };
                readonly matchTime: { readonly column: 'matchTime' };
                readonly predictionType: { readonly column: 'predictionType' };
                readonly prediction: { readonly column: 'prediction' };
                readonly odds: { readonly column: 'odds' };
                readonly confidence: { readonly column: 'confidence' };
                readonly confidenceLabel: { readonly column: 'confidenceLabel' };
                readonly status: { readonly column: 'status' };
                readonly tipster: { readonly column: 'tipster' };
                readonly isPremium: { readonly column: 'isPremium' };
                readonly analysis: { readonly column: 'analysis' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly name: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly password: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly image: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly plan: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly referralCode: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'User';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly email: { readonly column: 'email' };
                readonly name: { readonly column: 'name' };
                readonly password: { readonly column: 'password' };
                readonly image: { readonly column: 'image' };
                readonly plan: { readonly column: 'plan' };
                readonly referralCode: { readonly column: 'referralCode' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly sql: {
      readonly enums: false;
      readonly foreignKeys: true;
      readonly jsonAgg: true;
      readonly lateral: false;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: '__unbound__';
            readonly table: 'AppSetting';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: '__unbound__';
            readonly table: 'Payment';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: '__unbound__';
            readonly table: 'PlacedBet';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: '__unbound__';
            readonly table: 'Tip';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: '__unbound__';
            readonly table: 'User';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
