-- GoalEdge schema for Supabase Postgres.
-- App access is server-side only through SUPABASE_SECRET_KEY / service role.

create table if not exists public.users (
  id text primary key,
  email text not null unique,
  name text,
  password text,
  image text,
  plan text not null default 'free',
  referral_code text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tips (
  id text primary key,
  league text not null,
  country text not null,
  flag text not null default '⚽',
  home_team text not null,
  away_team text not null,
  match_time text not null,
  prediction_type text not null,
  prediction text not null,
  odds text not null,
  confidence integer not null,
  confidence_label text not null,
  status text not null default 'upcoming',
  tipster text not null,
  is_premium smallint not null default 0 check (is_premium in (0, 1)),
  analysis text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.referrals (
  id text primary key,
  code text not null,
  referrer_id text not null references public.users(id) on delete cascade,
  referred_id text not null unique references public.users(id) on delete cascade,
  status text not null default 'pending',
  reward_days integer not null default 7,
  created_at timestamptz not null default now(),
  qualified_at timestamptz,
  rewarded_at timestamptz
);

create table if not exists public.bookmarks (
  id text primary key,
  user_id text not null references public.users(id) on delete cascade,
  tip_id text not null references public.tips(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint bookmarks_user_id_tip_id_key unique (user_id, tip_id)
);

create table if not exists public.bet_slips (
  id text primary key,
  user_id text not null references public.users(id) on delete cascade,
  tip_id text not null references public.tips(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  subscribed_at timestamptz not null default now(),
  active smallint not null default 1 check (active in (0, 1))
);

create table if not exists public.payments (
  id text primary key,
  user_id text references public.users(id) on delete set null,
  email text not null,
  amount integer not null,
  plan text not null,
  reference text not null unique,
  access_code text,
  status text not null default 'pending',
  channel text,
  paid_at timestamptz,
  expires_at timestamptz,
  metadata text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.placed_bets (
  id text primary key,
  user_id text references public.users(id) on delete set null,
  email text not null,
  bet_type text not null,
  legs text not null,
  stake integer not null,
  total_odds double precision not null,
  potential_return integer not null,
  status text not null default 'pending',
  result text,
  settled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.app_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.shared_slips (
  slug text primary key,
  email text,
  legs text not null,
  stake integer,
  total_odds double precision,
  potential_return integer,
  created_at timestamptz not null default now()
);

create index if not exists referrals_referrer_id_idx on public.referrals (referrer_id);
create index if not exists tips_status_created_at_idx on public.tips (status, created_at desc);
create index if not exists payments_user_status_expires_idx on public.payments (user_id, status, expires_at desc);
create index if not exists payments_email_created_at_idx on public.payments (email, created_at desc);
create index if not exists placed_bets_email_created_at_idx on public.placed_bets (email, created_at desc);
create index if not exists shared_slips_email_idx on public.shared_slips (email);

create or replace function public.goaledge_set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = pg_catalog.now();
  return new;
end;
$$;

create trigger users_set_updated_at
  before update on public.users
  for each row execute function public.goaledge_set_updated_at();
create trigger tips_set_updated_at
  before update on public.tips
  for each row execute function public.goaledge_set_updated_at();
create trigger payments_set_updated_at
  before update on public.payments
  for each row execute function public.goaledge_set_updated_at();
create trigger placed_bets_set_updated_at
  before update on public.placed_bets
  for each row execute function public.goaledge_set_updated_at();
create trigger app_settings_set_updated_at
  before update on public.app_settings
  for each row execute function public.goaledge_set_updated_at();

-- All tables are private to the application server. No anon/authenticated
-- browser role gets access; service_role bypasses RLS and stays server-only.
do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'users', 'tips', 'referrals', 'bookmarks', 'bet_slips',
    'newsletter_subscribers', 'payments', 'placed_bets', 'app_settings', 'shared_slips'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on table public.%I from anon, authenticated', table_name);
    execute format('grant all on table public.%I to service_role', table_name);
  end loop;
end;
$$;

grant usage, select on sequence public.newsletter_subscribers_id_seq to service_role;
